name: RAML Auto Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Build & deploy to CloudHub 2.0
        run: mvn clean deploy -DmuleDeploy "-Dconnected.app.clientId=${{ secrets.CH_CLIENT_ID }}" "-Dconnected.app.clientSecret=${{ secrets.CH_CLIENT_SECRET }}"
